### ISSUE TITLE
Possibility to push it to Maven Central?

### ISSUE THREAD

**Issue by cgendreau** [AndyMoreland/squiggle-sql#1]
Hi,

Is there a possibility to push the library to Maven Central?

Regards,

Christian

**Comment by AndyMoreland** [comment]
Hi Christian -- sorry for the very late response:

As you can probably guess I'm not actively maintaining this right now. I forked this in order to add some features for a project at a previous job and just pushed the artifact to the internal maven repo. Since I'm not maintaining it, I'd prefer not to have it under my name on maven central.

Feel free to do whatever you'd like with the code in this project as far as I am concerned, though.
